//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI {
    public partial class Default {
        protected global::System.Web.UI.WebControls.Literal litDepartments;
        protected global::System.Web.UI.WebControls.Literal litInactiveEmployees;
        protected global::System.Web.UI.WebControls.Literal litTotalEmployees;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.WebControls.Literal litTodayJoining;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.Repeater rptActivities;
        protected global::System.Web.UI.WebControls.Literal litMaleEmployees;
        protected global::System.Web.UI.WebControls.Panel pnlNoActivity;
        protected global::System.Web.UI.WebControls.GridView gvLatestEmployees;
        protected global::System.Web.UI.WebControls.Literal litFemaleEmployees;
        protected global::System.Web.UI.WebControls.Literal litActiveEmployees;
    }
}

