//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI {
    public partial class ForgotPassword {
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
    }
}

