//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI {
    public partial class Login {
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUsername;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAlert;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
        protected global::System.Web.UI.HtmlControls.HtmlForm loginForm;
        protected global::System.Web.UI.WebControls.Literal litAlert;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        protected global::System.Web.UI.WebControls.Panel pnlAlert;
        protected global::System.Web.UI.WebControls.CheckBox chkRememberMe;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
    }
}

