//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI {
    public partial class SiteMaster {
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphScripts;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphPageTitle;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphContent;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphHead;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder cphBreadcrumb;
    }
}

