//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI.Designations {
    public partial class DesignationList {
        protected global::System.Web.UI.WebControls.TextBox txtDesigDescription;
        protected global::System.Web.UI.WebControls.TextBox txtDesignationName;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.CheckBox chkDesigActive;
        protected global::System.Web.UI.HtmlControls.HtmlForm frmDesignation;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentDesig;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterDept;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.Button btnSaveDesig;
        protected global::System.Web.UI.WebControls.Content cScripts;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDesigDept;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.HiddenField hfDesigId;
        protected global::System.Web.UI.WebControls.GridView gvDesignations;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl desigCount;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDesigName;
    }
}

