//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI.Employees {
    public partial class EmployeeForm {
        protected global::System.Web.UI.WebControls.Literal litPageTitle;
        protected global::System.Web.UI.WebControls.TextBox txtCountry;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revMobile;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartment;
        protected global::System.Web.UI.HtmlControls.HtmlForm frmEmployee;
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        protected global::System.Web.UI.WebControls.Content cScripts;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvJoiningDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvGender;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.TextBox txtJoiningDate;
        protected global::System.Web.UI.WebControls.HiddenField hfExistingPhoto;
        protected global::System.Web.UI.WebControls.RangeValidator rvSalary;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLastName;
        protected global::System.Web.UI.WebControls.TextBox txtExperience;
        protected global::System.Web.UI.WebControls.TextBox txtEmployeeCode;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDepartment;
        protected global::System.Web.UI.WebControls.TextBox txtDateOfBirth;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtSalary;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMobile;
        protected global::System.Web.UI.WebControls.TextBox txtState;
        protected global::System.Web.UI.WebControls.Literal litBreadcrumb;
        protected global::System.Web.UI.WebControls.TextBox txtZipCode;
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        protected global::System.Web.UI.WebControls.DropDownList ddlDesignation;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.Literal litFormTitle;
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSalary;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
        protected global::System.Web.UI.WebControls.HiddenField hfEmployeeId;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDesignation;
        protected global::System.Web.UI.WebControls.Literal litExistingPhoto;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;
    }
}

