//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI.Employees {
    public partial class EmployeeView {
        protected global::System.Web.UI.WebControls.Literal litExperience;
        protected global::System.Web.UI.WebControls.Literal litSalary;
        protected global::System.Web.UI.WebControls.Literal litDepartment;
        protected global::System.Web.UI.WebControls.Panel pnlStatusBadge;
        protected global::System.Web.UI.WebControls.Literal litEmpCode;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.WebControls.HyperLink hlEdit;
        protected global::System.Web.UI.WebControls.Literal litEmail;
        protected global::System.Web.UI.WebControls.Literal litUpdatedDate;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.Literal litCountry;
        protected global::System.Web.UI.WebControls.Literal litMobile;
        protected global::System.Web.UI.WebControls.Literal litJoiningDate;
        protected global::System.Web.UI.WebControls.Literal litState;
        protected global::System.Web.UI.WebControls.Literal litCreatedDate;
        protected global::System.Web.UI.WebControls.Literal litDesignation;
        protected global::System.Web.UI.WebControls.Literal litAddress;
        protected global::System.Web.UI.WebControls.Literal litGender;
        protected global::System.Web.UI.WebControls.Panel pnlAvatar;
        protected global::System.Web.UI.WebControls.Literal litDesig2;
        protected global::System.Web.UI.WebControls.Literal litZipCode;
        protected global::System.Web.UI.WebControls.Literal litDept2;
        protected global::System.Web.UI.WebControls.Literal litEmailLink;
        protected global::System.Web.UI.WebControls.Image imgPhoto;
        protected global::System.Web.UI.WebControls.Literal litCity;
        protected global::System.Web.UI.WebControls.Literal litFullName2;
        protected global::System.Web.UI.WebControls.Literal litFullName;
        protected global::System.Web.UI.WebControls.Literal litInitials;
        protected global::System.Web.UI.WebControls.Literal litAge;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.Literal litDob;
    }
}

