//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI.Employees {
    public partial class EmployeeList {
        protected global::System.Web.UI.WebControls.Literal litPageFrom;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterGender;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.HiddenField hfSortOrder;
        protected global::System.Web.UI.WebControls.GridView gvEmployees;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentPage;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterDept;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfSortColumn;
        protected global::System.Web.UI.WebControls.Content cScripts;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.LinkButton lbSort;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl totalCount;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Literal litPageTo;
        protected global::System.Web.UI.WebControls.Repeater rptPager;
        protected global::System.Web.UI.WebControls.LinkButton lbPage;
        protected global::System.Web.UI.WebControls.Literal litPageTotal;
    }
}

