//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI.Reports {
    public partial class EmployeeReport {
        protected global::System.Web.UI.WebControls.GridView gvDeptReport;
        protected global::System.Web.UI.WebControls.DropDownList ddlEmpGender;
        protected global::System.Web.UI.WebControls.Button btnSalaryReport;
        protected global::System.Web.UI.WebControls.GridView gvSalaryReport;
        protected global::System.Web.UI.WebControls.DropDownList ddlEmpStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlEmpDept;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.WebControls.Button btnGenerateEmpReport;
        protected global::System.Web.UI.WebControls.DropDownList ddlSalaryDept;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.GridView gvEmpReport;
    }
}

