//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated by designer file generator script.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.UI.Departments {
    public partial class DepartmentList {
        protected global::System.Web.UI.WebControls.HiddenField hfDeptId;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.TextBox txtDeptDescription;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDeptName;
        protected global::System.Web.UI.WebControls.Content cContent;
        protected global::System.Web.UI.HtmlControls.HtmlForm frmDepartment;
        protected global::System.Web.UI.WebControls.Content cBreadcrumb;
        protected global::System.Web.UI.WebControls.Content cTitle;
        protected global::System.Web.UI.WebControls.Content cScripts;
        protected global::System.Web.UI.WebControls.Button btnReset;
        protected global::System.Web.UI.WebControls.LinkButton lbDeleteDept;
        protected global::System.Web.UI.WebControls.GridView gvDepartments;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteDeptId;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl deptCount;
        protected global::System.Web.UI.WebControls.TextBox txtDepartmentName;
        protected global::System.Web.UI.WebControls.Button btnSaveDept;
        protected global::System.Web.UI.WebControls.CheckBox chkDeptActive;
    }
}

